name: Publish docs to Wiki

# Trigger this action only if there are changes pushed to the docs/** directory under the main branch
on:
  push:
    paths:
      - docs/**
    branches:
      - main

env:
  OWNER: ${{ github.event.repository.owner.name }} # This is the repository owner
  REPOSITORY: ${{ github.event.repository.name }} # This is the repository name

jobs:
  publish_docs_to_wiki:
    name: Publish docs to Wiki
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get commit info
        run: |
          echo "COMMIT_USER=$(git log -n 1 --pretty=format:%an)" >> $GITHUB_ENV
          echo "COMMIT_EMAIL=$(git log -n 1 --pretty=format:%ae)" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(git log -n 1 --pretty=format:%H)" >> $GITHUB_ENV

      # 1. Create folder named `tmp_wiki`
      # 2. Initialize Git
      # 3. Pull old Wiki content
      - name: Pull content from wiki
        run: |
          mkdir tmp_wiki
          cd tmp_wiki
          git init
          git config user.name "$COMMIT_USER"
          git config user.email "$COMMIT_EMAIL"
          git pull https://${{github.token}}@github.com/$OWNER/$REPOSITORY.wiki.git
      # 4. Synchronize differences between `docs` & `tmp_wiki`
      # 5. Push new Wiki content
      - name: Push content to wiki
        run: |
          rsync -av --delete docs/ tmp_wiki/ --exclude .git
          cd tmp_wiki
          git add .
          git commit -m "Docs sync from $OWNER/$REPOSITORY@$COMMIT_HASH" 
          git push https://${{github.token}}@github.com/$OWNER/$REPOSITORY.wiki.git master